"""change application model

Revision ID: 4ceb9b4e78af
Revises: 81d66f506870
Create Date: 2026-02-23 21:40:03.005591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceb9b4e78af'
down_revision: Union[str, Sequence[str], None] = '81d66f506870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_email_key'), 'applications', type_='unique')
    op.drop_column('applications', 'last_name')
    op.drop_column('applications', 'organization_name')
    op.drop_column('applications', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('applications_email_key'), 'applications', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
