"""add field legal status

Revision ID: 768fb2ac365b
Revises: f62a3a0e7972
Create Date: 2026-02-17 05:32:58.434288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768fb2ac365b'
down_revision: Union[str, Sequence[str], None] = 'f62a3a0e7972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('legal_status', sa.Enum('INDIVIDUAL', 'LEGAL_ENTITY', name='legalstatuschoices'), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', 'EMPLOYEE', name='rolechoices'), nullable=False))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'legal_status')
    # ### end Alembic commands ###
