"""change field

Revision ID: 95ddfdd3a117
Revises: 4ceb9b4e78af
Create Date: 2026-02-23 22:09:07.903533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ddfdd3a117'
down_revision: Union[str, Sequence[str], None] = '4ceb9b4e78af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tin', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['tin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tin')
    # ### end Alembic commands ###
