"""add activation code field

Revision ID: e798d4a5cfc9
Revises: 95ddfdd3a117
Create Date: 2026-02-23 23:31:56.109204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e798d4a5cfc9'
down_revision: Union[str, Sequence[str], None] = '95ddfdd3a117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
